import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { PDFDocument, rgb } from 'https://esm.sh/pdf-lib@1.17.1';
import fontkit from 'https://esm.sh/@pdf-lib/fontkit@1.1.1';

const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' };
const A4_WIDTH = 595.25; const A4_HEIGHT = 841.89;
type Values = Record<string, unknown>;
type Placement = { page: number; key?: string; x: number; y: number; fontSize?: number; maxWidth?: number; lineHeight?: number; clear?: { x: number; y: number; width: number; height: number; block?: boolean }; format?: 'text' | 'yen' | 'date' | 'sqm'; prefix?: string; suffix?: string };
type Layout = { placements?: Placement[]; plan?: { page: number; x: number; y: number; maxWidth: number; maxHeight: number } };
function response(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }); }
function text(value: unknown) { return String(value ?? '').trim(); }
function format(value: unknown, kind: Placement['format']) { const raw = text(value); if (!raw) return ''; if (kind === 'yen') { const n = Number(raw); return Number.isFinite(n) ? `${Math.round(n).toLocaleString('ja-JP')}円` : raw; } if (kind === 'sqm') { const n = Number(raw); return Number.isFinite(n) ? `${n.toLocaleString('ja-JP', { maximumFractionDigits: 2 })}㎡` : raw; } if (kind === 'date') { const m = raw.match(/^(\d{4})-(\d{2})-(\d{2})$/); return m ? `${m[1]}年${m[2]}月${m[3]}日` : raw; } return raw; }
async function loadFile(admin: ReturnType<typeof createClient>, path: string) { const { data, error } = await admin.storage.from('contract-documents').download(path); if (error || !data) throw new Error(`Storageからファイルを取得できませんでした: ${error?.message ?? ''}`); return new Uint8Array(await data.arrayBuffer()); }
async function preparePdf(template: Uint8Array) { const source = await PDFDocument.load(template); const output = await PDFDocument.create(); for (let i = 0; i < source.getPageCount(); i += 1) { const page = source.getPage(i); const { width, height } = page.getSize(); if (width / height > 1.3) for (const side of [0, 1]) { const embedded = await output.embedPage(page, { left: width / 2 * side, right: width / 2 * (side + 1), bottom: 0, top: height }); output.addPage([A4_WIDTH, A4_HEIGHT]).drawPage(embedded, { x: 0, y: 0, width: A4_WIDTH, height: A4_HEIGHT }); } else { const embedded = await output.embedPage(page); output.addPage([A4_WIDTH, A4_HEIGHT]).drawPage(embedded, { x: 0, y: 0, width: A4_WIDTH, height: A4_HEIGHT }); } } return output; }
function render(pdf: PDFDocument, font: any, values: Values, layout: Layout, snapshot?: Uint8Array) { const pages = pdf.getPages(); for (const p of layout.placements ?? []) { const page = pages[p.page - 1]; if (!page) throw new Error(`レイアウトのページ番号が不正です: ${p.page}`); if (p.clear) page.drawRectangle({ x: p.clear.x, y: p.clear.y, width: p.clear.width, height: p.clear.height, color: rgb(1, 1, 1) }); const content = `${p.prefix ?? ''}${format(values[p.key ?? ''], p.format)}${p.suffix ?? ''}`; if (content) page.drawText(content, { x: p.x, y: p.y, size: p.fontSize ?? 10, font, color: rgb(0, 0, 0), maxWidth: p.maxWidth, lineHeight: p.lineHeight ?? (p.fontSize ?? 10) * 1.3 }); }
  if (!snapshot || !layout.plan) return Promise.resolve(); const p = layout.plan; const page = pages[p.page - 1]; if (!page) throw new Error(`区画図ページが不正です: ${p.page}`); return pdf.embedPng(snapshot).then((image) => { const scale = Math.min(p.maxWidth / image.width, p.maxHeight / image.height); page.drawImage(image, { x: p.x + (p.maxWidth - image.width * scale) / 2, y: p.y + (p.maxHeight - image.height * scale) / 2, width: image.width * scale, height: image.height * scale }); }); }

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders }); if (request.method !== 'POST') return response({ error: 'Method not allowed' }, 405);
  const url = Deno.env.get('SUPABASE_URL')!; const anonKey = Deno.env.get('SUPABASE_ANON_KEY')!; const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!; const auth = request.headers.get('Authorization') ?? '';
  const userClient = createClient(url, anonKey, { global: { headers: { Authorization: auth } } }); const { data: { user } } = await userClient.auth.getUser(); if (!user) return response({ error: 'Unauthorized' }, 401);
  const body = await request.json(); const leaseContractId = text(body.leaseContractId); const documentType = text(body.documentType); const isPreview = Boolean(body.previewValues); if (!leaseContractId && !isPreview) return response({ error: 'leaseContractId は必須です。' }, 400);
  const { data: document, error: docError } = leaseContractId ? await userClient.from('lease_contract_document').select('lease_contract_document_id, document_type, field_values, contract_document_template_revision_id').eq('lease_contract_id', leaseContractId).maybeSingle() : { data: null, error: null }; if (docError || (!isPreview && !document)) return response({ error: '契約書データを先に保存してください。' }, 400);
  const type = documentType || document?.document_type || 'ordinary_lease'; let revisionId = text(body.templateRevisionId) || document?.contract_document_template_revision_id; if (!revisionId) { const { data: template } = await userClient.from('contract_document_template').select('active_revision_id').eq('document_type', type).maybeSingle(); revisionId = template?.active_revision_id ?? ''; } const revisionQuery = userClient.from('contract_document_template_revision').select('contract_document_template_revision_id, template_file_path, font_file_path, field_definitions, layout_definition, contract_document_template:contract_document_template_id(document_type, requires_plan)').eq('contract_document_template_revision_id', revisionId).maybeSingle();
  const { data: revision, error: revisionError } = await revisionQuery; if (revisionError || !revision || (revision as any).contract_document_template?.document_type !== type || !(revision as any).template_file_path) return response({ error: '公開済みのひな型が登録されていません。' }, 400);
  const values = (body.previewValues ?? document?.field_values ?? {}) as Values; for (const field of (revision as any).field_definitions ?? []) if (field.required && !text(values[field.key])) return response({ error: `必須項目「${field.label}」を入力してください。` }, 400);
  const requiresPlan = Boolean((revision as any).contract_document_template?.requires_plan); const { data: plans, error: planError } = document ? await userClient.from('lease_contract_document_plan').select('snapshot_file_path').eq('lease_contract_document_id', document.lease_contract_document_id).order('created_at') : { data: [], error: null }; if (!isPreview && requiresPlan && (planError || !plans?.length)) return response({ error: '対象区画を選択して保存してからPDFを生成してください。' }, 400);
  try { const admin = createClient(url, serviceKey); const [template, font, snapshot] = await Promise.all([loadFile(admin, (revision as any).template_file_path), loadFile(admin, (revision as any).font_file_path), plans?.[0] ? loadFile(admin, plans[0].snapshot_file_path) : Promise.resolve(undefined)]); const pdf = await preparePdf(template); pdf.registerFontkit(fontkit); await render(pdf, await pdf.embedFont(font, { subset: true }), values, (revision as any).layout_definition, snapshot); const path = isPreview ? `previews/${user.id}/${type}/${revisionId}.pdf` : `documents/${leaseContractId}/${type}/${document?.lease_contract_document_id}/ordinary_lease.pdf`; const { error: uploadError } = await admin.storage.from('contract-documents').upload(path, await pdf.save(), { contentType: 'application/pdf', upsert: true }); if (uploadError) throw uploadError; const generatedAt = new Date().toISOString(); if (!isPreview) await admin.from('lease_contract_document').update({ pdf_file_path: path, pdf_generated_at: generatedAt }).eq('lease_contract_id', leaseContractId); return response({ pdfFilePath: path, generatedAt, pageCount: pdf.getPageCount() }); } catch (error) { return response({ error: `契約書PDFを生成できませんでした: ${error instanceof Error ? error.message : String(error)}` }, 500); }
});
