import { useEffect, useMemo, useState, type FormEvent } from 'react';
import type { Session } from '@supabase/supabase-js';
import {
  BrowserRouter,
  NavLink,
  Navigate,
  Outlet,
  Route,
  Routes,
  useLocation,
  useNavigate,
} from 'react-router-dom';
import { isSupabaseConfigured, supabase } from './lib/supabase';

type Property = { property_id: string; property_name: string; short_name: string | null };
type Account = { account_id: string; account_name: string; income_expense_type: '収入' | '支出' };
type Summary = { property_id: string; accounting_month: string; contract_rent_income: number; contract_common_charge_income: number; other_income: number; recurring_expense: number; variable_expense: number; income_total: number; expense_total: number; balance: number };
type RecurringItem = { recurring_item_id: string; property_id: string; account_id: string; item_name: string; monthly_amount: number; effective_from_month: string; effective_to_month: string | null; counterparty_name: string | null; notes: string | null; is_active: boolean; account?: Pick<Account, 'account_name' | 'income_expense_type'> | null };
type MonthlyEntry = { financial_entry_id: string; property_id: string; account_id: string; accounting_month: string; amount: number; entry_date: string | null; description: string; counterparty_name: string | null; notes: string | null; account?: Pick<Account, 'account_name' | 'income_expense_type'> | null };
type Detail = { source_type: string; source_id: string; account_id: string; account_name: string; income_expense_type: '収入' | '支出'; amount: number; description: string; counterparty_name: string | null };
type Tab = 'dashboard' | 'recurring' | 'monthly';

const yen = new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY', maximumFractionDigits: 0 });
const monthLabel = (value: string) => new Intl.DateTimeFormat('ja-JP', { year: 'numeric', month: 'short' }).format(new Date(`${value.slice(0, 7)}-01T00:00:00`));
const monthValue = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-01`;
const fiscalYear = (date = new Date()) => date.getMonth() < 3 ? date.getFullYear() - 1 : date.getFullYear();
const fiscalMonths = (year: number) => Array.from({ length: 12 }, (_, index) => `${index < 9 ? year : year + 1}-${String((index + 3) % 12 + 1).padStart(2, '0')}-01`);

function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [loadingSession, setLoadingSession] = useState(true);

  useEffect(() => {
    if (!supabase) { setLoadingSession(false); return; }
    void supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoadingSession(false); });
    const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession));
    return () => listener.subscription.unsubscribe();
  }, []);

  if (!isSupabaseConfigured) return <ConfigurationRequired />;
  if (loadingSession) return <main className="state-screen"><p>ログイン状態を確認しています…</p></main>;
  return session ? <FinancialPortal session={session} onSignOut={() => void supabase?.auth.signOut()} /> : <Login />;
}

function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (!supabase) return;
    setSubmitting(true);
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    setMessage(error ? error.message : 'ログインしました。');
    setSubmitting(false);
  };
  return <main className="login-shell"><form className="login-card" onSubmit={submit}><p className="eyebrow">SK HOUSING</p><h1>ビル収支管理</h1><p>ログインして、物件ごとの年度収支を確認します。</p><label>メールアドレス<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>パスワード<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{message && <p className="form-message">{message}</p>}<button className="primary-button" disabled={submitting}>{submitting ? 'ログイン中…' : 'ログイン'}</button></form></main>;
}

function FinancialPortal({ session, onSignOut }: { session: Session; onSignOut: () => void }) {
  const [tab, setTab] = useState<Tab>('dashboard');
  const [properties, setProperties] = useState<Property[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [selectedPropertyId, setSelectedPropertyId] = useState('');
  const [year, setYear] = useState(fiscalYear());
  const [notice, setNotice] = useState('');
  const loadMasters = async () => {
    if (!supabase) return;
    const [propertyResult, accountResult] = await Promise.all([
      supabase.from('property_master').select('property_id, property_name, short_name').order('property_name'),
      supabase.from('income_expense_account_master').select('account_id, account_name, income_expense_type').order('account_id'),
    ]);
    if (propertyResult.error || accountResult.error) { setNotice(propertyResult.error?.message ?? accountResult.error?.message ?? 'マスタの取得に失敗しました。'); return; }
    const nextProperties = (propertyResult.data ?? []) as Property[];
    setProperties(nextProperties); setAccounts((accountResult.data ?? []) as Account[]);
    setSelectedPropertyId((current) => current || nextProperties[0]?.property_id || '');
  };
  useEffect(() => { void loadMasters(); }, []);
  const selectedProperty = properties.find((property) => property.property_id === selectedPropertyId);
  return <main className="portal-shell"><header className="app-header"><div><p className="eyebrow">SK HOUSING</p><h1>ビル収支管理</h1></div><div className="header-user"><span>{session.user.email}</span><button onClick={onSignOut}>ログアウト</button></div></header><nav className="tabs"><button className={tab === 'dashboard' ? 'active' : ''} onClick={() => setTab('dashboard')}>年度ダッシュボード</button><button className={tab === 'recurring' ? 'active' : ''} onClick={() => setTab('recurring')}>定期収支管理</button><button className={tab === 'monthly' ? 'active' : ''} onClick={() => setTab('monthly')}>月次収支入力</button></nav><section className="toolbar"><label>対象ビル<select value={selectedPropertyId} onChange={(e) => setSelectedPropertyId(e.target.value)}>{properties.map((property) => <option value={property.property_id} key={property.property_id}>{property.short_name || property.property_name}</option>)}</select></label>{tab === 'dashboard' && <label>年度<select value={year} onChange={(e) => setYear(Number(e.target.value))}>{[year - 1, year, year + 1].map((value) => <option value={value} key={value}>{value}年度（4月〜3月）</option>)}</select></label>}<span className="selected-property">{selectedProperty?.property_name}</span></section>{notice && <p className="notice">{notice}</p>}{tab === 'dashboard' && <Dashboard properties={properties} selectedPropertyId={selectedPropertyId} year={year} />}{tab === 'recurring' && <RecurringManager propertyId={selectedPropertyId} accounts={accounts} />}{tab === 'monthly' && <MonthlyManager propertyId={selectedPropertyId} accounts={accounts} />}</main>;
}

function Dashboard({ properties, selectedPropertyId, year }: { properties: Property[]; selectedPropertyId: string; year: number }) {
  const [summaries, setSummaries] = useState<Summary[]>([]);
  const [details, setDetails] = useState<Detail[]>([]);
  const [detailMonth, setDetailMonth] = useState<string | null>(null);
  const [error, setError] = useState('');
  const months = useMemo(() => fiscalMonths(year), [year]);
  useEffect(() => { void (async () => { if (!supabase) return; setError(''); const { data, error: queryError } = await supabase.from('property_monthly_income_expense_summary').select('*').gte('accounting_month', months[0]).lte('accounting_month', months[11]); if (queryError) setError(queryError.message); else setSummaries((data ?? []) as Summary[]); })(); }, [year]);
  const propertyTotals = properties.map((property) => ({ property, values: summaries.filter((summary) => summary.property_id === property.property_id), }));
  const selectedValues = summaries.filter((summary) => summary.property_id === selectedPropertyId);
  const totalFor = (key: keyof Pick<Summary, 'income_total' | 'expense_total' | 'balance'>) => selectedValues.reduce((sum, value) => sum + Number(value[key]), 0);
  const showDetails = async (month: string) => { if (!supabase) return; const { data, error: queryError } = await supabase.from('property_monthly_income_expense_detail').select('source_type, source_id, account_id, account_name, income_expense_type, amount, description, counterparty_name').eq('property_id', selectedPropertyId).eq('accounting_month', month).order('income_expense_type').order('account_id'); if (queryError) { setError(queryError.message); return; } setDetails((data ?? []) as Detail[]); setDetailMonth(month); };
  return <section className="content"><div className="section-heading"><div><h2>年度収支ダッシュボード</h2><p>物件ごとの発生ベース収支を確認します。</p></div></div>{error && <p className="notice">{error}</p>}<div className="metric-grid"><Metric label="収入合計" value={totalFor('income_total')} tone="income" /><Metric label="支出合計" value={totalFor('expense_total')} tone="expense" /><Metric label="収支" value={totalFor('balance')} tone="balance" /></div><section className="panel"><h3>全ビルの年度収支</h3><div className="table-scroll"><table><thead><tr><th>ビル</th><th>収入合計</th><th>支出合計</th><th>収支</th></tr></thead><tbody>{propertyTotals.map(({ property, values }) => <tr key={property.property_id}><td>{property.short_name || property.property_name}</td><td>{yen.format(values.reduce((sum, value) => sum + Number(value.income_total), 0))}</td><td>{yen.format(values.reduce((sum, value) => sum + Number(value.expense_total), 0))}</td><td className="amount-balance">{yen.format(values.reduce((sum, value) => sum + Number(value.balance), 0))}</td></tr>)}</tbody></table></div></section><section className="panel"><h3>{year}年度の月別収支</h3><div className="table-scroll"><table><thead><tr><th>月</th><th>契約収入</th><th>その他収入</th><th>準固定支出</th><th>変動支出</th><th>収支</th><th></th></tr></thead><tbody>{months.map((month) => { const value = selectedValues.find((summary) => summary.accounting_month === month); const contractIncome = Number(value?.contract_rent_income ?? 0) + Number(value?.contract_common_charge_income ?? 0); return <tr key={month}><td>{monthLabel(month)}</td><td>{yen.format(contractIncome)}</td><td>{yen.format(Number(value?.other_income ?? 0))}</td><td>{yen.format(Number(value?.recurring_expense ?? 0))}</td><td>{yen.format(Number(value?.variable_expense ?? 0))}</td><td className="amount-balance">{yen.format(Number(value?.balance ?? 0))}</td><td><button className="link-button" onClick={() => void showDetails(month)}>明細</button></td></tr>; })}</tbody></table></div></section>{detailMonth && <DetailDialog month={detailMonth} details={details} onClose={() => setDetailMonth(null)} />}</section>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{yen.format(value)}</strong></article>; }

function RecurringManager({ propertyId, accounts }: { propertyId: string; accounts: Account[] }) {
  const [items, setItems] = useState<RecurringItem[]>([]); const [editing, setEditing] = useState<RecurringItem | null>(null); const [error, setError] = useState('');
  const load = async () => { if (!supabase || !propertyId) return; const { data, error: queryError } = await supabase.from('property_recurring_financial_item').select('*, account:income_expense_account_master(account_name, income_expense_type)').eq('property_id', propertyId).order('effective_from_month', { ascending: false }); if (queryError) setError(queryError.message); else setItems((data ?? []) as RecurringItem[]); };
  useEffect(() => { void load(); }, [propertyId]);
  const remove = async (id: string) => { if (!supabase || !confirm('この定期明細を削除しますか？')) return; const { error: deleteError } = await supabase.from('property_recurring_financial_item').delete().eq('recurring_item_id', id); if (deleteError) setError(deleteError.message); else void load(); };
  return <section className="content"><div className="section-heading"><div><h2>定期収支管理</h2><p>BM費・通信費・看板料など、適用期間のある月額項目を管理します。</p></div><button className="primary-button" onClick={() => setEditing({ recurring_item_id: '', property_id: propertyId, account_id: accounts[0]?.account_id ?? '', item_name: '', monthly_amount: 0, effective_from_month: monthValue(), effective_to_month: null, counterparty_name: null, notes: null, is_active: true })}>定期明細を登録</button></div>{error && <p className="notice">{error}</p>}<section className="panel"><div className="table-scroll"><table><thead><tr><th>科目</th><th>明細名</th><th>月額</th><th>適用期間</th><th>相手先</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.recurring_item_id}><td><span className={`tag ${item.account?.income_expense_type === '収入' ? 'income' : 'expense'}`}>{item.account?.account_name}</span></td><td>{item.item_name}</td><td>{yen.format(Number(item.monthly_amount))}</td><td>{monthLabel(item.effective_from_month)}〜{item.effective_to_month ? monthLabel(item.effective_to_month) : '終了未定'}</td><td>{item.counterparty_name || '—'}</td><td><button className="link-button" onClick={() => setEditing(item)}>編集</button><button className="danger-button" onClick={() => void remove(item.recurring_item_id)}>削除</button></td></tr>)}{!items.length && <tr><td colSpan={6} className="empty">登録済みの定期明細はありません。</td></tr>}</tbody></table></div></section>{editing && <RecurringDialog item={editing} accounts={accounts} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} />}</section>;
}

function MonthlyManager({ propertyId, accounts }: { propertyId: string; accounts: Account[] }) {
  const [month, setMonth] = useState(monthValue()); const [items, setItems] = useState<MonthlyEntry[]>([]); const [editing, setEditing] = useState<MonthlyEntry | null>(null); const [error, setError] = useState('');
  const load = async () => { if (!supabase || !propertyId) return; const { data, error: queryError } = await supabase.from('property_monthly_financial_entry').select('*, account:income_expense_account_master(account_name, income_expense_type)').eq('property_id', propertyId).eq('accounting_month', month).order('entry_date', { ascending: false }); if (queryError) setError(queryError.message); else setItems((data ?? []) as MonthlyEntry[]); };
  useEffect(() => { void load(); }, [propertyId, month]);
  const remove = async (id: string) => { if (!supabase || !confirm('この月次明細を削除しますか？')) return; const { error: deleteError } = await supabase.from('property_monthly_financial_entry').delete().eq('financial_entry_id', id); if (deleteError) setError(deleteError.message); else void load(); };
  return <section className="content"><div className="section-heading"><div><h2>月次収支入力</h2><p>修繕費・消耗品費などの実績を月ごとに入力します。</p></div><button className="primary-button" onClick={() => setEditing({ financial_entry_id: '', property_id: propertyId, account_id: accounts.find((account) => account.income_expense_type === '支出')?.account_id ?? accounts[0]?.account_id ?? '', accounting_month: month, amount: 0, entry_date: month, description: '', counterparty_name: null, notes: null })}>月次明細を入力</button></div><div className="inline-filter"><label>計上月<input type="month" value={month.slice(0, 7)} onChange={(e) => setMonth(`${e.target.value}-01`)} /></label></div>{error && <p className="notice">{error}</p>}<section className="panel"><div className="table-scroll"><table><thead><tr><th>科目</th><th>内容</th><th>金額</th><th>発生日</th><th>相手先</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.financial_entry_id}><td><span className={`tag ${item.account?.income_expense_type === '収入' ? 'income' : 'expense'}`}>{item.account?.account_name}</span></td><td>{item.description}</td><td>{yen.format(Number(item.amount))}</td><td>{item.entry_date || '—'}</td><td>{item.counterparty_name || '—'}</td><td><button className="link-button" onClick={() => setEditing(item)}>編集</button><button className="danger-button" onClick={() => void remove(item.financial_entry_id)}>削除</button></td></tr>)}{!items.length && <tr><td colSpan={6} className="empty">この月の明細はありません。</td></tr>}</tbody></table></div></section>{editing && <MonthlyDialog item={editing} accounts={accounts} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} />}</section>;
}

function RecurringDialog({ item, accounts, onClose, onSaved }: { item: RecurringItem; accounts: Account[]; onClose: () => void; onSaved: () => void }) { const [draft, setDraft] = useState(item); const [error, setError] = useState(''); const save = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; const payload = { property_id: draft.property_id, account_id: draft.account_id, item_name: draft.item_name, monthly_amount: Number(draft.monthly_amount), effective_from_month: draft.effective_from_month, effective_to_month: draft.effective_to_month || null, counterparty_name: draft.counterparty_name || null, notes: draft.notes || null, is_active: draft.is_active }; const result = draft.recurring_item_id ? await supabase.from('property_recurring_financial_item').update(payload).eq('recurring_item_id', draft.recurring_item_id) : await supabase.from('property_recurring_financial_item').insert(payload); if (result.error) setError(result.error.message); else onSaved(); }; return <Dialog title={item.recurring_item_id ? '定期明細を編集' : '定期明細を登録'} onClose={onClose}><form onSubmit={save} className="form-grid"><Field label="科目"><select value={draft.account_id} onChange={(e) => setDraft({ ...draft, account_id: e.target.value })}>{accounts.map((account) => <option value={account.account_id} key={account.account_id}>{account.income_expense_type}｜{account.account_name}</option>)}</select></Field><Field label="明細名"><input value={draft.item_name} onChange={(e) => setDraft({ ...draft, item_name: e.target.value })} required /></Field><Field label="月額（円）"><input type="number" min="1" value={draft.monthly_amount || ''} onChange={(e) => setDraft({ ...draft, monthly_amount: Number(e.target.value) })} required /></Field><Field label="相手先"><input value={draft.counterparty_name ?? ''} onChange={(e) => setDraft({ ...draft, counterparty_name: e.target.value })} /></Field><Field label="適用開始月"><input type="month" value={draft.effective_from_month.slice(0, 7)} onChange={(e) => setDraft({ ...draft, effective_from_month: `${e.target.value}-01` })} required /></Field><Field label="適用終了月"><input type="month" value={draft.effective_to_month?.slice(0, 7) ?? ''} onChange={(e) => setDraft({ ...draft, effective_to_month: e.target.value ? `${e.target.value}-01` : null })} /></Field><Field label="備考"><textarea value={draft.notes ?? ''} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} /></Field><label className="check"><input type="checkbox" checked={draft.is_active} onChange={(e) => setDraft({ ...draft, is_active: e.target.checked })} />利用中</label>{error && <p className="notice">{error}</p>}<div className="form-actions"><button type="button" onClick={onClose}>取消</button><button className="primary-button">保存</button></div></form></Dialog>; }

function MonthlyDialog({ item, accounts, onClose, onSaved }: { item: MonthlyEntry; accounts: Account[]; onClose: () => void; onSaved: () => void }) { const [draft, setDraft] = useState(item); const [error, setError] = useState(''); const save = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; const payload = { property_id: draft.property_id, account_id: draft.account_id, accounting_month: draft.accounting_month, amount: Number(draft.amount), entry_date: draft.entry_date || null, description: draft.description, counterparty_name: draft.counterparty_name || null, notes: draft.notes || null }; const result = draft.financial_entry_id ? await supabase.from('property_monthly_financial_entry').update(payload).eq('financial_entry_id', draft.financial_entry_id) : await supabase.from('property_monthly_financial_entry').insert(payload); if (result.error) setError(result.error.message); else onSaved(); }; return <Dialog title={item.financial_entry_id ? '月次明細を編集' : '月次明細を入力'} onClose={onClose}><form onSubmit={save} className="form-grid"><Field label="科目"><select value={draft.account_id} onChange={(e) => setDraft({ ...draft, account_id: e.target.value })}>{accounts.map((account) => <option value={account.account_id} key={account.account_id}>{account.income_expense_type}｜{account.account_name}</option>)}</select></Field><Field label="計上月"><input type="month" value={draft.accounting_month.slice(0, 7)} onChange={(e) => setDraft({ ...draft, accounting_month: `${e.target.value}-01` })} required /></Field><Field label="内容"><input value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} required /></Field><Field label="金額（円）"><input type="number" min="1" value={draft.amount || ''} onChange={(e) => setDraft({ ...draft, amount: Number(e.target.value) })} required /></Field><Field label="発生日／請求日"><input type="date" value={draft.entry_date ?? ''} onChange={(e) => setDraft({ ...draft, entry_date: e.target.value || null })} /></Field><Field label="相手先"><input value={draft.counterparty_name ?? ''} onChange={(e) => setDraft({ ...draft, counterparty_name: e.target.value })} /></Field><Field label="備考"><textarea value={draft.notes ?? ''} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} /></Field>{error && <p className="notice">{error}</p>}<div className="form-actions"><button type="button" onClick={onClose}>取消</button><button className="primary-button">保存</button></div></form></Dialog>; }

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true"><header><h2>{title}</h2><button onClick={onClose} aria-label="閉じる">×</button></header>{children}</section></div>; }
function DetailDialog({ month, details, onClose }: { month: string; details: Detail[]; onClose: () => void }) { return <Dialog title={`${monthLabel(month)}の収支明細`} onClose={onClose}><div className="detail-list">{details.map((detail) => <div className="detail-row" key={`${detail.source_type}-${detail.source_id}-${detail.account_id}`}><div><span className={`tag ${detail.income_expense_type === '収入' ? 'income' : 'expense'}`}>{detail.account_name}</span><strong>{detail.description}</strong><small>{detail.source_type}{detail.counterparty_name ? `｜${detail.counterparty_name}` : ''}</small></div><b>{yen.format(Number(detail.amount))}</b></div>)}{!details.length && <p className="empty">明細はありません。</p>}</div></Dialog>; }
function ConfigurationRequired() { return <main className="state-screen"><section className="login-card"><h1>接続設定が必要です</h1><p><code>VITE_SUPABASE_URL</code> と <code>VITE_SUPABASE_ANON_KEY</code> を設定してください。</p></section></main>; }

function SummaryCard({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`summary-card ${tone}`}><p>{label}</p><strong>{value}<small>件</small></strong></article>; }
function AccountStatusBadge({ status }: { status: AccountStatus }) { const label = status === 'pending' ? '承認待ち' : status === 'active' ? '有効' : '利用停止'; return <span className={`account-status ${status}`}>{label}</span>; }
function roleLabel(role: AccountRole) { return role === 'admin' ? 'システム管理者' : role === 'manager' ? '業務管理者' : role === 'staff' ? '担当者' : '参照専用'; }

function AccountModal({ profile, employees, profiles, onClose, onSave }: { profile: UserProfile; employees: Employee[]; profiles: UserProfile[]; onClose: () => void; onSave: (draft: Pick<UserProfile, 'employee_id' | 'role' | 'account_status'>) => Promise<void> }) {
  const [employeeId, setEmployeeId] = useState(profile.employee_id ?? '');
  const [role, setRole] = useState<AccountRole>(profile.role);
  const [status, setStatus] = useState<AccountStatus>(profile.account_status);
  const [isSaving, setIsSaving] = useState(false);
  const unavailableEmployeeIds = new Set(profiles.filter((item) => item.user_id !== profile.user_id && item.employee_id).map((item) => item.employee_id));
  const availableEmployees = employees.filter((employee) => employee.employment_status === 'active' && (!unavailableEmployeeIds.has(employee.employee_id) || employee.employee_id === profile.employee_id));
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSaving(true); await onSave({ employee_id: employeeId || null, role, account_status: status }); setIsSaving(false); };
  return <div className="modal-backdrop"><form className="modal account-modal" onSubmit={(event) => void submit(event)}><header><div><p className="eyebrow">ACCOUNT SETTINGS</p><h2>アカウントを設定</h2></div><button type="button" className="modal-close" onClick={onClose}>×</button></header><div className="modal-body"><div className="read-only-field"><span>メールアドレス</span><strong>{profile.email}</strong></div><label>担当者<select value={employeeId} onChange={(event) => setEmployeeId(event.target.value)}><option value="">未紐づけ</option>{availableEmployees.map((employee) => <option value={employee.employee_id} key={employee.employee_id}>{employee.employee_name}（{employee.department?.department_name ?? '部門未設定'}）</option>)}</select></label><div className="form-grid"><label>ロール<select value={role} onChange={(event) => setRole(event.target.value as AccountRole)}><option value="admin">システム管理者</option><option value="manager">業務管理者</option><option value="staff">担当者</option><option value="viewer">参照専用</option></select></label><label>アカウント状態<select value={status} onChange={(event) => setStatus(event.target.value as AccountStatus)}><option value="pending">承認待ち</option><option value="active">有効</option><option value="suspended">利用停止</option></select></label></div><p className="modal-hint">有効化には、在籍中かつ他のアカウントに未紐づけの担当者を設定してください。</p></div><footer><button type="button" className="secondary-button" onClick={onClose}>キャンセル</button><button className="primary-button" type="submit" disabled={isSaving}>{isSaving ? '保存中…' : '保存する'}</button></footer></form></div>;
}

function Dashboard({ contracts, userName }: { contracts: Contract[]; userName: string }) {
  const active = contracts.filter((item) => item.status !== '完了').length;
  const due = contracts.filter((item) => item.status !== '完了').slice(0, 4);
  const statusCount = statuses.map((status) => ({ status, count: contracts.filter((item) => item.status === status).length }));
  return <>
    <section className="welcome-row"><div><p className="section-kicker">2026年7月14日（火）</p><h2>おはようございます、{userName}さん</h2><p>本日の契約業務の状況です。</p></div><NavLink className="primary-button" to="/contracts">契約を確認する <span>→</span></NavLink></section>
    <section className="metric-grid"><Metric label="進行中の契約" value={active} unit="件" detail="前月比 +2件" icon="◫" tone="blue" /><Metric label="今月の締結予定" value={2} unit="件" detail="締結予定日：7月31日" icon="✓" tone="green" /><Metric label="対応期限超過" value={1} unit="件" detail="至急確認が必要です" icon="!" tone="red" /><Metric label="承認待ち" value={2} unit="件" detail="最長 3日間保留中" icon="◷" tone="orange" /></section>
    <section className="dashboard-grid"><article className="panel due-panel"><div className="panel-title"><div><h3>対応期限が近い契約</h3><p>直近30日以内に対応が必要な契約</p></div><NavLink to="/contracts">すべて見る</NavLink></div><div className="due-list">{due.map((contract, index) => <div className="due-row" key={contract.id}><div className={`date-badge ${index === 0 ? 'urgent' : ''}`}><strong>{index === 0 ? '18' : index === 1 ? '22' : index === 2 ? '25' : '30'}</strong><span>7月</span></div><div className="due-details"><strong>{contract.tenant}</strong><span>{contract.property} ・ {contract.type}契約</span></div><StatusBadge status={contract.status} /><span className="chevron">›</span></div>)}</div></article>
      <article className="panel progress-panel"><div className="panel-title"><div><h3>契約進捗</h3><p>ステータス別の件数</p></div><button className="text-button">詳細を見る</button></div><div className="progress-list">{statusCount.map((item) => <div className="progress-row" key={item.status}><div><span className={`dot dot-${statusClass(item.status)}`} />{item.status}</div><div className="progress-track"><i style={{ width: `${Math.max((item.count / Math.max(contracts.length, 1)) * 100, item.count ? 13 : 0)}%` }} /></div><strong>{item.count}<small>件</small></strong></div>)}</div></article>
      <article className="panel updates-panel"><div className="panel-title"><div><h3>最近の更新</h3><p>チームの最新アクティビティ</p></div></div><div className="update-list">{contracts.slice(0, 4).map((contract, index) => <div className="update-row" key={contract.id}><span className={`activity-icon activity-${index}`}>{index === 0 ? '✎' : index === 1 ? '✓' : '◷'}</span><div><p><strong>{contract.assignee}</strong> が「{contract.tenant}」を{index === 0 ? '更新しました' : index === 1 ? '承認しました' : '確認しました'}</p><small>{contract.updatedAt}</small></div></div>)}</div></article>
    </section>
  </>;
}

function Metric({ label, value, unit, detail, icon, tone }: { label: string; value: number; unit: string; detail: string; icon: string; tone: string }) { return <article className="metric-card"><div><p>{label}</p><strong>{value}<small>{unit}</small></strong><span className={tone === 'red' ? 'negative' : ''}>{tone === 'blue' ? '↗ ' : ''}{detail}</span></div><i className={`metric-icon ${tone}`}>{icon}</i></article>; }

function ContractsPage({ contracts, setContracts, canEdit }: { contracts: Contract[]; setContracts: React.Dispatch<React.SetStateAction<Contract[]>>; canEdit: boolean }) {
  const [view, setView] = useState<ViewMode>('table'); const [query, setQuery] = useState(''); const [property, setProperty] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState(''); const [editing, setEditing] = useState<Contract | null>(null); const [isCreating, setIsCreating] = useState(false); const [toast, setToast] = useState('');
  const filtered = useMemo(() => contracts.filter((contract) => (!query || [contract.id, contract.tenant, contract.property, contract.assignee].some((value) => value.toLowerCase().includes(query.toLowerCase()))) && (!property || contract.property === property) && (!type || contract.type === type) && (!status || contract.status === status)), [contracts, query, property, type, status]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800); };
  const save = (draft: ContractDraft, id?: string) => { if (id) { setContracts((items) => items.map((item) => item.id === id ? { ...item, ...draft, updatedAt: 'たった今' } : item)); notify('契約情報を更新しました。'); } else { const nextId = `CT-26${String(75 + contracts.length).padStart(2, '0')}`; setContracts((items) => [{ id: nextId, ...draft, updatedAt: 'たった今' }, ...items]); notify('新しい契約を追加しました。'); } setEditing(null); setIsCreating(false); };
  const move = (contract: Contract, next: ContractStatus) => { setContracts((items) => items.map((item) => item.id === contract.id ? { ...item, status: next, updatedAt: 'たった今' } : item)); notify(`「${contract.tenant}」を${next}へ移動しました。`); };
  return <>
    <section className="page-heading"><div><p>賃貸借契約の進捗と担当状況を管理します。</p></div>{canEdit && <button className="primary-button" onClick={() => setIsCreating(true)}>＋ 契約を追加</button>}</section>
    <section className="filter-panel"><div className="search-box"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="契約ID・テナント名・物件名で検索" /></div><select value={property} onChange={(e) => setProperty(e.target.value)}><option value="">すべての物件</option>{properties.map((value) => <option key={value}>{value}</option>)}</select><select value={type} onChange={(e) => setType(e.target.value)}><option value="">契約種別</option><option>新規</option><option>更新</option></select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">すべてのステータス</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select><button className="clear-button" onClick={() => { setQuery(''); setProperty(''); setType(''); setStatus(''); }}>条件をクリア</button></section>
    <section className="contracts-toolbar"><p><strong>{filtered.length}</strong> 件の契約</p><div className="view-switch"><button className={view === 'table' ? 'selected' : ''} onClick={() => setView('table')}>☷ 一覧</button><button className={view === 'board' ? 'selected' : ''} onClick={() => setView('board')}>▦ ボード</button></div></section>
    {view === 'table' ? <ContractTable contracts={filtered} onEdit={setEditing} canEdit={canEdit} /> : <ContractBoard contracts={filtered} onEdit={setEditing} onMove={move} canEdit={canEdit} />}
    {(editing || isCreating) && <ContractModal contract={editing ?? undefined} onClose={() => { setEditing(null); setIsCreating(false); }} onSave={save} />}
    {toast && <div className="toast">✓ {toast}</div>}
  </>;
}

function ContractTable({ contracts, onEdit, canEdit }: { contracts: Contract[]; onEdit: (contract: Contract) => void; canEdit: boolean }) { return <div className="table-panel"><div className="table-wrap"><table><thead><tr><th>契約ID</th><th>テナント・物件</th><th>種別</th><th>契約期間</th><th>担当者</th><th>ステータス</th>{canEdit && <th aria-label="操作" />}</tr></thead><tbody>{contracts.map((contract) => <tr key={contract.id}><td><strong className="contract-id">{contract.id}</strong></td><td><strong>{contract.tenant}</strong><small>{contract.property}</small></td><td><span className={`type-pill ${contract.type === '新規' ? 'new' : ''}`}>{contract.type}</span></td><td>{formatDate(contract.startDate)}<span className="date-separator">〜</span>{formatDate(contract.endDate)}</td><td><span className="table-person">{contract.assignee.slice(0, 1)}</span>{contract.assignee}</td><td><StatusBadge status={contract.status} /></td>{canEdit && <td><button className="row-action" onClick={() => onEdit(contract)}>編集</button></td>}</tr>)}</tbody></table></div>{contracts.length === 0 && <EmptyState />}</div>; }

function ContractBoard({ contracts, onEdit, onMove, canEdit }: { contracts: Contract[]; onEdit: (contract: Contract) => void; onMove: (contract: Contract, status: ContractStatus) => void; canEdit: boolean }) { return <div className="board">{statuses.map((status) => <section className="board-column" key={status}><header><div><span className={`dot dot-${statusClass(status)}`} />{status}</div><b>{contracts.filter((item) => item.status === status).length}</b></header><div className="board-cards">{contracts.filter((item) => item.status === status).map((contract) => <article className="board-card" key={contract.id}><div className="board-card-head"><span className={`type-pill ${contract.type === '新規' ? 'new' : ''}`}>{contract.type}</span>{canEdit && <button onClick={() => onEdit(contract)}>•••</button>}</div><h3>{contract.tenant}</h3><p>{contract.property}</p><div className="board-dates">◷ {formatDate(contract.startDate)}〜</div><footer><span className="table-person">{contract.assignee.slice(0, 1)}</span>{canEdit ? <select aria-label={`${contract.tenant} のステータス`} value={contract.status} onChange={(e) => onMove(contract, e.target.value as ContractStatus)}>{statuses.map((value) => <option key={value}>{value}</option>)}</select> : <StatusBadge status={contract.status} />}</footer></article>)}</div></section>)}</div>; }

function ContractModal({ contract, onClose, onSave }: { contract?: Contract; onClose: () => void; onSave: (draft: ContractDraft, id?: string) => void }) { const [draft, setDraft] = useState<ContractDraft>(contract ? { property: contract.property, tenant: contract.tenant, type: contract.type, startDate: contract.startDate, endDate: contract.endDate, assignee: contract.assignee, status: contract.status, note: contract.note } : blankDraft()); const update = <K extends keyof ContractDraft>(key: K, value: ContractDraft[K]) => setDraft((item) => ({ ...item, [key]: value })); const submit = (e: FormEvent) => { e.preventDefault(); if (!draft.tenant.trim() || !draft.startDate || !draft.endDate) return; onSave(draft, contract?.id); };
  return <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={submit}><header><div><p className="eyebrow">CONTRACT</p><h2>{contract ? '契約情報を編集' : '契約を追加'}</h2></div><button type="button" className="modal-close" onClick={onClose}>×</button></header><div className="modal-body"><div className="form-grid"><label>契約種別<select value={draft.type} onChange={(e) => update('type', e.target.value as ContractType)}><option>新規</option><option>更新</option></select></label><label>進捗ステータス<select value={draft.status} onChange={(e) => update('status', e.target.value as ContractStatus)}>{statuses.map((value) => <option key={value}>{value}</option>)}</select></label><label>物件<select value={draft.property} onChange={(e) => update('property', e.target.value)}>{properties.map((value) => <option key={value}>{value}</option>)}</select></label><label>担当者<select value={draft.assignee} onChange={(e) => update('assignee', e.target.value)}>{assignees.map((value) => <option key={value}>{value}</option>)}</select></label></div><label>テナント名<input value={draft.tenant} onChange={(e) => update('tenant', e.target.value)} placeholder="例）株式会社サンプル" required /></label><div className="form-grid"><label>契約開始日<input type="date" value={draft.startDate} onChange={(e) => update('startDate', e.target.value)} required /></label><label>契約終了日<input type="date" value={draft.endDate} onChange={(e) => update('endDate', e.target.value)} required /></label></div><label>備考<textarea value={draft.note} onChange={(e) => update('note', e.target.value)} placeholder="連絡事項や進捗メモを入力" rows={3} /></label></div><footer><button type="button" className="secondary-button" onClick={onClose}>キャンセル</button><button className="primary-button" type="submit">{contract ? '変更を保存' : '契約を追加'}</button></footer></form></div>; }

function StatusBadge({ status }: { status: ContractStatus }) { return <span className={`status-badge ${statusClass(status)}`}><i />{status}</span>; }
function EmptyState() { return <div className="empty-state"><strong>該当する契約がありません</strong><p>検索条件を変更してもう一度お試しください。</p></div>; }
function statusClass(status: ContractStatus) { return status === '起案' ? 'draft' : status === '審査' ? 'review' : status === '契約書作成' ? 'document' : status === '締結' ? 'signing' : 'complete'; }
function formatDate(value: string) { return value ? value.replace(/-/g, '/') : '未設定'; }

export default App;
