import { useEffect, useMemo, useRef, useState, type PointerEvent } from 'react';
import * as pdfjsLib from 'pdfjs-dist';
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { supabase } from './lib/supabase';
import { reportFrontendDiagnostic } from './FrontendDiagnostics';
import type { DocumentType } from './ContractTemplateTabs';

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorker;
const A4_WIDTH = 595.25; const A4_HEIGHT = 841.89;
type Placement = { page: number; key?: string; x: number; y: number; fontSize?: number; maxWidth?: number; lineHeight?: number; clear?: { x: number; y: number; width: number; height: number } };
type Layout = { placements?: Placement[] }; type Revision = { contract_document_template_revision_id: string; revision_no: number; field_definitions: Array<{ key: string; label: string }>; layout_definition: Layout; template_file_path: string | null; font_file_path: string | null };
const toNumber = (value: string) => Number.isFinite(Number(value)) ? Number(value) : 0;

export function ContractTemplateLayoutEditor({ documentType }: { documentType: DocumentType }) {
  const [open, setOpen] = useState(false); const [source, setSource] = useState<Revision | null>(null); const [draft, setDraft] = useState<Revision | null>(null); const [selected, setSelected] = useState(0); const [pdfUrl, setPdfUrl] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const canvasRef = useRef<HTMLCanvasElement>(null); const pdfRef = useRef<any>(null); const dragging = useRef(false);
  const placements = draft?.layout_definition.placements ?? []; const placement = placements[selected]; const labels = useMemo(() => new Map((draft?.field_definitions ?? []).map((field) => [field.key, field.label])), [draft]);
  const fail = (message: string, detail?: unknown) => { setError(message); reportFrontendDiagnostic(message, detail); };
  useEffect(() => { setOpen(false); setSource(null); setDraft(null); setPdfUrl(''); setError(''); }, [documentType]);
  const loadTemplate = async () => { if (!supabase) return fail('Supabaseが設定されていないためレイアウトを編集できません。'); setBusy(true); setError(''); const { data: template, error: templateError } = await supabase.from('contract_document_template').select('active_revision_id').eq('document_type', documentType).maybeSingle(); if (templateError || !template?.active_revision_id) { setBusy(false); return fail('公開済みのひな型がないためレイアウトを編集できません。', templateError); } const { data, error: revisionError } = await supabase.from('contract_document_template_revision').select('contract_document_template_revision_id, revision_no, field_definitions, layout_definition, template_file_path, font_file_path').eq('contract_document_template_revision_id', template.active_revision_id).single(); if (revisionError || !data?.template_file_path) { setBusy(false); return fail('レイアウト定義またはPDFひな型を取得できません。', revisionError); } const { data: signed, error: signedError } = await supabase.storage.from('contract-documents').createSignedUrl(data.template_file_path, 3600); setBusy(false); if (signedError || !signed?.signedUrl) return fail('PDFひな型のプレビューURLを取得できません。', signedError); const value = data as unknown as Revision; setSource(value); setDraft(structuredClone(value)); setSelected(0); setPdfUrl(signed.signedUrl); setOpen(true); };
  const draw = async () => { if (!pdfUrl || !canvasRef.current || !placement) return; try { if (!pdfRef.current) pdfRef.current = await pdfjsLib.getDocument(pdfUrl).promise; const sourcePage = Math.ceil(placement.page / 2); const page = await pdfRef.current.getPage(sourcePage); const viewport = page.getViewport({ scale: 1.4 }); const full = document.createElement('canvas'); full.width = Math.ceil(viewport.width); full.height = Math.ceil(viewport.height); await page.render({ canvas: full, canvasContext: full.getContext('2d')!, viewport }).promise; const target = canvasRef.current; const landscape = viewport.width / viewport.height > 1.3; target.width = landscape ? Math.floor(full.width / 2) : full.width; target.height = full.height; const context = target.getContext('2d')!; context.clearRect(0, 0, target.width, target.height); context.drawImage(full, landscape ? placement.page % 2 === 0 ? full.width / 2 : 0 : 0, 0, target.width, full.height, 0, 0, target.width, target.height); const x = placement.x / A4_WIDTH * target.width; const y = (A4_HEIGHT - placement.y) / A4_HEIGHT * target.height; context.strokeStyle = '#e5372a'; context.fillStyle = 'rgba(229,55,42,.18)'; context.lineWidth = 2; context.beginPath(); context.arc(x, y, 9, 0, Math.PI * 2); context.fill(); context.stroke(); context.fillStyle = '#9b1f18'; context.font = 'bold 13px sans-serif'; context.fillText(labels.get(placement.key ?? '') ?? placement.key ?? '項目', x + 12, y - 10); } catch (renderError) { fail('PDFプレビューを描画できません。', renderError); } };
  useEffect(() => { void draw(); }, [pdfUrl, selected, draft]);
  const update = (key: keyof Placement, value: string) => { if (!draft || !placement) return; const next = structuredClone(draft); (next.layout_definition.placements ?? [])[selected] = { ...placement, [key]: key === 'key' ? value : toNumber(value) }; setDraft(next); };
  const move = (event: PointerEvent<HTMLCanvasElement>) => { if (!dragging.current || !placement || !canvasRef.current) return; const rect = canvasRef.current.getBoundingClientRect(); const x = Math.max(0, Math.min(A4_WIDTH, (event.clientX - rect.left) / rect.width * A4_WIDTH)); const y = Math.max(0, Math.min(A4_HEIGHT, A4_HEIGHT - (event.clientY - rect.top) / rect.height * A4_HEIGHT)); if (!draft) return; const next = structuredClone(draft); (next.layout_definition.placements ?? [])[selected] = { ...placement, x: Math.round(x * 10) / 10, y: Math.round(y * 10) / 10 }; setDraft(next); };
  const save = async (publish: boolean) => { if (!supabase || !source || !draft) return; if (!placements.every((item) => item.page > 0 && item.x >= 0 && item.y >= 0 && (item.fontSize ?? 10) > 0 && (item.maxWidth ?? 1) > 0)) return fail('ページ・座標・文字サイズ・幅の値を確認してください。'); setBusy(true); const { data: template, error: templateError } = await supabase.from('contract_document_template').select('contract_document_template_id').eq('document_type', documentType).single(); const { data: latest } = template ? await supabase.from('contract_document_template_revision').select('revision_no').eq('contract_document_template_id', template.contract_document_template_id).order('revision_no', { ascending: false }).limit(1).maybeSingle() : { data: null }; if (templateError || !template) { setBusy(false); return fail('ひな型情報を取得できません。', templateError); } const { data: user } = await supabase.auth.getUser(); const { data: created, error: createError } = await supabase.from('contract_document_template_revision').insert({ contract_document_template_id: template.contract_document_template_id, revision_no: (latest?.revision_no ?? source.revision_no) + 1, status: publish ? 'published' : 'draft', template_file_path: source.template_file_path, font_file_path: source.font_file_path, field_definitions: source.field_definitions, layout_definition: draft.layout_definition, created_by: user.user?.id, published_at: publish ? new Date().toISOString() : null }).select('contract_document_template_revision_id').single(); if (createError || !created) { setBusy(false); return fail('レイアウトを保存できません。', createError); } if (publish) { const { error: publishError } = await supabase.from('contract_document_template').update({ active_revision_id: created.contract_document_template_revision_id }).eq('contract_document_template_id', template.contract_document_template_id); if (publishError) { setBusy(false); return fail('レイアウトを公開できません。', publishError); } } setBusy(false); setNotice(publish ? 'レイアウトを公開しました。次回PDF生成から反映されます。' : '下書きを保存しました。'); if (publish) setOpen(false); };
  return <section className="layout-editor"><button className="secondary-button" type="button" onClick={() => void loadTemplate()} disabled={busy}>{busy ? '読込中…' : '差し込み位置を調整'}</button>{notice && <p className="document-message">{notice}</p>}{error && <p className="document-message error">{error}</p>}{open && draft && <div className="layout-modal-backdrop" role="dialog" aria-modal="true" aria-label="差し込み位置の調整"><div className="layout-modal"><header><div><h2>差し込み位置の調整</h2><p>赤い点をドラッグするとPDF上の位置を直接調整できます。</p></div><button type="button" onClick={() => setOpen(false)}>×</button></header><div className="layout-modal-content"><aside><label>項目<select value={selected} onChange={(event) => setSelected(Number(event.target.value))}>{placements.map((item, index) => <option key={index} value={index}>{labels.get(item.key ?? '') ?? item.key ?? '項目未設定'} / {item.page}ページ</option>)}</select></label>{placement && <div className="layout-grid"><label>ページ<input type="number" min="1" value={placement.page} onChange={(event) => update('page', event.target.value)} /></label><label>X<input type="number" min="0" step="0.1" value={placement.x} onChange={(event) => update('x', event.target.value)} /></label><label>Y<input type="number" min="0" step="0.1" value={placement.y} onChange={(event) => update('y', event.target.value)} /></label><label>文字サイズ<input type="number" min="1" step="0.1" value={placement.fontSize ?? 10} onChange={(event) => update('fontSize', event.target.value)} /></label><label>最大幅<input type="number" min="1" step="0.1" value={placement.maxWidth ?? ''} onChange={(event) => update('maxWidth', event.target.value)} /></label></div>}<p className="layout-help">座標原点はPDF左下です。ドラッグ後の数値は0.1ポイント単位で反映されます。</p></aside><main><canvas ref={canvasRef} onPointerDown={(event) => { dragging.current = true; event.currentTarget.setPointerCapture(event.pointerId); move(event); }} onPointerMove={move} onPointerUp={() => { dragging.current = false; }} onPointerCancel={() => { dragging.current = false; }} /></main></div><footer><button type="button" onClick={() => void save(false)} disabled={busy}>下書きを保存</button><button className="primary-button" type="button" onClick={() => void save(true)} disabled={busy}>公開する</button></footer></div></div>}</section>;
}
