import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from './lib/supabase';
import './property-plan.css';

type Property = { property_id: string; property_name: string; short_name: string | null };
type YearDraft = { id?: string; fiscal_year: string; income: string; opex: string; capex: string; interest: string; principal: string };
type CostType = 'purchase_price' | 'acquisition_cost' | 'initial_capex' | 'inherited_deposit';
type CostItem = { id?: string; cost_type: CostType; item_name: string; amount: string };
const emptyYear = (year = new Date().getFullYear()): YearDraft => ({ fiscal_year: String(year), income: '0', opex: '0', capex: '0', interest: '', principal: '' });
const emptyCost = (cost_type: CostType): CostItem => ({ cost_type, item_name: '', amount: '0' });
const labels: Record<CostType, string> = { purchase_price: '購入価格', acquisition_cost: '取得諸費用', initial_capex: '初期CAPEX', inherited_deposit: '承継敷金・保証金等' };
const toNumber = (value: string) => value.trim() === '' ? null : Number(value);

export function PropertyAcquisitionPlanPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const propertyId = params.get('propertyId') ?? '';
  const [properties, setProperties] = useState<Property[]>([]); const [selectedId, setSelectedId] = useState(propertyId); const [years, setYears] = useState<YearDraft[]>([]); const [items, setItems] = useState<CostItem[]>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const property = properties.find((item) => item.property_id === selectedId);
  useEffect(() => { void (async () => { if (!supabase) return; const result = await supabase.from('asset_master').select('asset_id, asset_name, short_name').order('asset_name'); if (result.error) setError(result.error.message); else { const list = (result.data ?? []).map((item) => ({ property_id: item.asset_id, property_name: item.asset_name, short_name: item.short_name })); setProperties(list); if (!selectedId && list[0]) setSelectedId(list[0].property_id); } })(); }, []);
  useEffect(() => { if (selectedId) void loadPlan(selectedId); }, [selectedId]);
  async function loadPlan(id: string) { if (!supabase) return; setLoading(true); setError(''); const planResult = await supabase.from('property_acquisition_plan').select('property_acquisition_plan_id, purchase_price, acquisition_cost, initial_capex, inherited_deposit').eq('property_id', id).maybeSingle(); if (planResult.error) { setError(planResult.error.message); setLoading(false); return; } const planId = planResult.data?.property_acquisition_plan_id; const [yearsResult, itemsResult] = await Promise.all([planId ? supabase.from('property_acquisition_plan_year').select('property_acquisition_plan_year_id, fiscal_year, income, opex, capex, interest, principal').eq('property_acquisition_plan_id', planId) : Promise.resolve({ data: [], error: null }), planId ? supabase.from('property_acquisition_plan_cost_item').select('property_acquisition_plan_cost_item_id, cost_type, item_name, amount').eq('property_acquisition_plan_id', planId).order('display_order') : Promise.resolve({ data: [], error: null })]); if (yearsResult.error || itemsResult.error) { setError(yearsResult.error?.message ?? itemsResult.error?.message ?? '購入時計画を取得できませんでした'); setLoading(false); return; } setYears((yearsResult.data ?? []).sort((a, b) => b.fiscal_year - a.fiscal_year).map((row) => ({ id: row.property_acquisition_plan_year_id, fiscal_year: String(row.fiscal_year), income: String(row.income ?? 0), opex: String(row.opex ?? 0), capex: String(row.capex ?? 0), interest: row.interest == null ? '' : String(row.interest), principal: row.principal == null ? '' : String(row.principal) }))); const loadedItems: CostItem[] = (itemsResult.data ?? []).map((row) => ({ id: row.property_acquisition_plan_cost_item_id, cost_type: row.cost_type as CostType, item_name: row.item_name, amount: String(row.amount ?? 0) })); if (!loadedItems.length && planResult.data) { loadedItems.push({ cost_type: 'purchase_price', item_name: '既存登録額（内訳未登録）', amount: String(planResult.data.purchase_price ?? 0) }); loadedItems.push({ cost_type: 'acquisition_cost', item_name: '既存登録額（内訳未登録）', amount: String(planResult.data.acquisition_cost ?? 0) }); loadedItems.push({ cost_type: 'initial_capex', item_name: '既存登録額（内訳未登録）', amount: String(planResult.data.initial_capex ?? 0) }); loadedItems.push({ cost_type: 'inherited_deposit', item_name: '既存登録額（内訳未登録）', amount: String(planResult.data.inherited_deposit ?? 0) }); } setItems(loadedItems); setLoading(false); }
  function updateYear(index: number, field: keyof YearDraft, value: string) { setYears((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row)); }
  function updateItem(index: number, field: keyof CostItem, value: string) { setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row)); }
  function addYear() { const existing = new Set(years.map((row) => row.fiscal_year)); let year = new Date().getFullYear(); while (existing.has(String(year))) year -= 1; setYears((current) => [emptyYear(year), ...current]); }
  function addItem(type: CostType) { setItems((current) => [...current, emptyCost(type)]); }
  const total = (type: CostType) => items.filter((item) => item.cost_type === type).reduce((sum, item) => sum + Number(item.amount || 0), 0);
  async function save(event: FormEvent) { event.preventDefault(); if (!supabase || !selectedId) return; setSaving(true); setError(''); setNotice(''); const fiscalYears = years.map((row) => Number(row.fiscal_year)); if (fiscalYears.some((year) => !Number.isInteger(year) || year < 1900 || year > 2200) || new Set(fiscalYears).size !== fiscalYears.length) { setError('年度は1900〜2200の整数で、重複しないように入力してください。'); setSaving(false); return; } if (items.some((item) => !item.item_name.trim() || Number(item.amount) < 0 || Number.isNaN(Number(item.amount)))) { setError('内訳名と金額を正しく入力してください。'); setSaving(false); return; } const plan = await supabase.from('property_acquisition_plan').upsert({ property_id: selectedId, purchase_price: total('purchase_price'), acquisition_cost: total('acquisition_cost'), initial_capex: total('initial_capex'), inherited_deposit: total('inherited_deposit') }, { onConflict: 'property_id' }).select('property_acquisition_plan_id').single(); if (plan.error || !plan.data) { setError(plan.error?.message ?? '購入時計画を保存できませんでした'); setSaving(false); return; } const planId = plan.data.property_acquisition_plan_id; const deleteResults = await Promise.all([supabase.from('property_acquisition_plan_year').delete().eq('property_acquisition_plan_id', planId), supabase.from('property_acquisition_plan_cost_item').delete().eq('property_acquisition_plan_id', planId)]); const deleteError = deleteResults.find((result) => result.error)?.error; if (deleteError) { setError(deleteError.message); setSaving(false); return; } const yearRows = years.map((row) => ({ property_acquisition_plan_id: planId, fiscal_year: Number(row.fiscal_year), income: Number(row.income || 0), opex: Number(row.opex || 0), capex: Number(row.capex || 0), interest: toNumber(row.interest), principal: toNumber(row.principal) })); const itemRows = items.map((item, index) => ({ property_acquisition_plan_id: planId, cost_type: item.cost_type, item_name: item.item_name.trim(), amount: Number(item.amount || 0), display_order: index })); const [yearResult, itemResult] = await Promise.all([yearRows.length ? supabase.from('property_acquisition_plan_year').insert(yearRows) : Promise.resolve({ error: null }), itemRows.length ? supabase.from('property_acquisition_plan_cost_item').insert(itemRows) : Promise.resolve({ error: null })]); const insertError = yearResult.error ?? itemResult.error; if (insertError) { setError(insertError.message); setSaving(false); return; } setSaving(false); setNotice('購入時計画を保存しました。'); await loadPlan(selectedId); }
  return <section className="property-plan-page"><header className="page-heading"><div><p className="section-kicker">ACQUISITION PLAN</p><h2>購入時計画の入力</h2><p>投資額は内訳の合計から自動計算し、年度別収支計画と合わせて保存します。</p></div><button type="button" className="secondary-button" onClick={() => navigate(`/property-profitability?propertyId=${selectedId}`)}>収益分析へ戻る</button></header><div className="property-plan-toolbar"><label>物件<select value={selectedId} onChange={(event) => { setSelectedId(event.target.value); navigate(`/property-profitability/plan?propertyId=${event.target.value}`); }}>{properties.map((item) => <option key={item.property_id} value={item.property_id}>{item.short_name || item.property_name}</option>)}</select></label>{property && <span>{property.property_name}</span>}</div>{notice && <p className="form-notice">{notice}</p>}{error && <p className="notice">{error}</p>}{loading ? <p className="notice">購入時計画を読み込んでいます…</p> : <form onSubmit={save}><section className="panel property-plan-panel"><h3>投資額の内訳</h3><div className="cost-item-groups">{(Object.keys(labels) as CostType[]).map((type) => <CostGroup key={type} type={type} label={labels[type]} items={items} total={total(type)} onAdd={() => addItem(type)} onUpdate={updateItem} onDelete={(index) => setItems((current) => current.filter((_, rowIndex) => rowIndex !== index))}/>)}</div><p className="property-plan-help">総投資額 = 購入価格 + 取得諸費用 + 初期CAPEX − 承継敷金・保証金等</p></section><section className="panel property-plan-panel"><header className="property-plan-section-heading"><div><h3>年度別収支計画</h3><p>未入力の利息・元金返済は未算出として扱います。</p></div><button type="button" className="secondary-button" onClick={addYear}>年度を追加</button></header><div className="table-scroll"><table className="property-plan-table"><thead><tr><th>年度</th><th>収入</th><th>OPEX</th><th>CAPEX</th><th>支払利息</th><th>元金返済</th><th>操作</th></tr></thead><tbody>{years.map((row, index) => <tr key={row.id ?? `new-${index}`}><td><input type="number" min="1900" max="2200" value={row.fiscal_year} onChange={(event) => updateYear(index, 'fiscal_year', event.target.value)} required/></td>{(['income','opex','capex','interest','principal'] as const).map((field) => <td key={field}><input type="number" min="0" step="1" value={row[field]} placeholder={field === 'interest' || field === 'principal' ? '未算出' : '0'} onChange={(event) => updateYear(index, field, event.target.value)}/></td>)}<td><button type="button" className="text-button danger" onClick={() => setYears((current) => current.filter((_, rowIndex) => rowIndex !== index))}>削除</button></td></tr>)}{!years.length && <tr><td colSpan={7} className="empty">年度計画は未登録です。</td></tr>}</tbody></table></div></section><div className="property-plan-actions"><button type="submit" className="primary-button" disabled={saving || !selectedId}>{saving ? '保存中…' : '購入時計画を保存'}</button></div></form>}</section>;
}
function CostGroup({ type, label, items, total, onAdd, onUpdate, onDelete }: { type: CostType; label: string; items: CostItem[]; total: number; onAdd: () => void; onUpdate: (index: number, field: keyof CostItem, value: string) => void; onDelete: (index: number) => void }) { const entries = items.map((item, index) => ({ item, index })).filter(({ item }) => item.cost_type === type); return <div className="cost-item-group"><header><strong>{label}</strong><span>{new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY', maximumFractionDigits: 0 }).format(total)}</span></header>{entries.map(({ item, index }) => <div className="cost-item-row" key={item.id ?? `${type}-${index}`}><input value={item.item_name} placeholder="内訳名" onChange={(event) => onUpdate(index, 'item_name', event.target.value)}/><input type="number" min="0" step="1" value={item.amount} onChange={(event) => onUpdate(index, 'amount', event.target.value)}/><button type="button" className="text-button danger" onClick={() => onDelete(index)}>削除</button></div>)}<button type="button" className="text-button" onClick={onAdd}>＋ 内訳を追加</button></div>; }
