import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { useSearchParams } from 'react-router-dom';
import { supabase } from './lib/supabase';

type Row = { month?: string; fiscal_year?: number; income?: number|null; opex?: number|null; noi?: number|null; ncf?: number|null; after_debt_cf?: number|null; plan?: Record<string, number|null>; actual?: Record<string, number|null> };
type Result = { status: string; reference_date: string; property?: { property_name: string; short_name: string|null }; plan: { purchase_price:number; acquisition_cost:number; initial_capex:number; inherited_deposit:number; total_investment:number }|null; monthly: Row[]; yearly: Row[] };
const yen = new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY', maximumFractionDigits: 0 });
const amount = (v:number|null|undefined) => v == null ? '未算出' : yen.format(Number(v));
const percent = (v:number|null|undefined) => v == null ? '未算出' : `${(Number(v)*100).toFixed(2)}%`;

export function PropertyProfitabilityPage() {
  const [params, setParams] = useSearchParams(); const [properties, setProperties] = useState<Array<{property_id:string;property_name:string;short_name:string|null}>>([]); const [data, setData] = useState<Result|null>(null); const [date, setDate] = useState(new Date().toISOString().slice(0,10)); const [error, setError] = useState(''); const id = params.get('propertyId') ?? '';
  useEffect(() => { void (async () => { if (!supabase) return; const r = await supabase.from('asset_master').select('asset_id, asset_name, short_name').order('asset_name'); if (r.error) setError(r.error.message); else { const rows = (r.data ?? []).map(p => ({ property_id: p.asset_id, property_name: p.asset_name, short_name: p.short_name })); setProperties(rows); if (!id && rows[0]) setParams({propertyId:rows[0].property_id}); } })(); }, []);
  useEffect(() => { void (async () => { if (!supabase || !id) return; setError(''); const r = await supabase.rpc('get_property_profitability_analysis',{p_property_id:id,p_reference_date:date,p_granularity:'month'}); if (r.error) setError(r.error.message); else setData(r.data as Result); })(); }, [id,date]);
  const totals = useMemo(() => (data?.monthly ?? []).reduce<{income:number;opex:number;noi:number;ncf:number}>((a,r) => ({income:a.income+Number(r.income??0),opex:a.opex+Number(r.opex??0),noi:a.noi+Number(r.noi??0),ncf:a.ncf+Number(r.ncf??0)}),{income:0,opex:0,noi:0,ncf:0}),[data]);
  const denominator = data?.plan?.total_investment ?? null;
  return <section className="property-profitability-page"><header className="page-heading"><div><p className="section-kicker">PROPERTY PROFITABILITY</p><h2>物件別収益分析</h2><p>購入時計画と発生実績を、同じ分類コードで比較します。</p></div></header><div className="toolbar"><label>物件<select value={id} onChange={e=>setParams({propertyId:e.target.value})}>{properties.map(p=><option value={p.property_id} key={p.property_id}>{p.short_name||p.property_name}</option>)}</select></label><label>基準日<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{error&&<p className="notice">{error}</p>}{data?.status==='not_found'&&<p className="notice">対象物件がありません。</p>}{data?.status==='ok'&&<><div className="metric-grid"><Metric label="総投資額" value={denominator}/><Metric label="年間収入" value={totals.income}/><Metric label="NOI" value={totals.noi}/><Metric label="NOI利回り" value={denominator?totals.noi/denominator:null} rate/><Metric label="累計CF回収率" value={denominator?totals.ncf/denominator:null} rate/></div>{!data.plan&&<p className="notice">購入時計画未登録のため、投資額と利回りは未算出です。</p>}<Panel title="投資サマリー"><div className="analysis-grid">{[['購入価格',data.plan?.purchase_price],['取得諸費用',data.plan?.acquisition_cost],['初期CAPEX',data.plan?.initial_capex],['承継敷金等',data.plan?.inherited_deposit],['借入残高',null],['税引前返済後CF',null]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{amount(value as number|null)}</strong></div>)}</div></Panel><Panel title="購入時計画 vs 発生実績"><Table rows={data.yearly} yearly/></Panel><Panel title="実績推移"><MonthlyTrend rows={data.monthly}/></Panel><Panel title="収入内訳"><p>分類コード M01〜M03（賃料・共益費・その他収入）を収入として集計しています。</p></Panel><Panel title="支出内訳"><p>分類コード M04〜M08を初期版では全件OPEXとして集計しています。</p></Panel><Panel title="将来実装予定"><p>CAPEX分類、月次計画比較、税引後CF、将来CF予測は将来実装予定です。</p></Panel><details className="calculation-basis"><summary>算定根拠を表示</summary><p>基準日：{data.reference_date}（発生日が基準日以前）</p><p>参照元：property_monthly_income_expense_detail、property_acquisition_plan、property_acquisition_plan_year</p><p>計算式：NOI = 収入 − OPEX、NCF = NOI − CAPEX、累計CF回収率 = 累計CF ÷ 総投資額</p><p>除外：入出金実績、減価償却、課税所得、法人税、将来予測。借入・返済は未登録のため未算出。</p></details></>}</section>;
}
function Metric({label,value,rate=false}:{label:string;value:number|null|undefined;rate?:boolean}){return <article className="metric"><span>{label}</span><strong>{rate?percent(value):amount(value)}</strong></article>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Table({rows,yearly}:{rows:Row[];yearly:boolean}){return <div className="table-scroll"><table><thead><tr><th>年度</th>{['income','opex','noi','capex','ncf','interest','principal'].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.fiscal_year}>{yearly&&<td>{r.fiscal_year}</td>}{['income','opex','noi','capex','ncf','interest','principal'].map(k=><td key={k}>計画 {amount(r.plan?.[k])}<br/>実績 {amount(r.actual?.[k])}</td>)}</tr>)}</tbody></table></div>}

function MonthlyTrend({rows}:{rows:Row[]}){const grouped = rows.reduce<Record<string,Row[]>>((result,row)=>{const parsed = row.month ? new Date(row.month + 'T00:00:00') : null; const key = parsed ? String(parsed.getFullYear() - (parsed.getMonth() < 3 ? 1 : 0)) : 'unknown'; (result[key] ??= []).push(row); return result;},{}); return <div className='yearly-monthly-trend'>{Object.entries(grouped).sort(([a],[b])=>Number(b)-Number(a)).map(([year,months])=><details key={year}><summary className="monthly-year-summary"><strong>{year}年度</strong><span>{months.length}か月</span><span><em>収入</em>{amount(months.reduce((sum,row)=>sum+Number(row.income??0),0))}</span><span><em>OPEX</em>{amount(months.reduce((sum,row)=>sum+Number(row.opex??0),0))}</span><span><em>NOI</em>{amount(months.reduce((sum,row)=>sum+Number(row.noi??0),0))}</span><span><em>返済後CF</em>{amount(months.some(row=>row.after_debt_cf!=null)?months.reduce((sum,row)=>sum+Number(row.after_debt_cf??0),0):null)}</span></summary><div className='table-scroll'><table><thead><tr><th>月</th><th>収入</th><th>OPEX</th><th>NOI</th><th>税引前返済後CF</th></tr></thead><tbody>{[...months].sort((a,b)=>String(b.month).localeCompare(String(a.month))).map(r=><tr key={r.month}><td>{r.month}</td><td>{amount(r.income)}</td><td>{amount(r.opex)}</td><td>{amount(r.noi)}</td><td>{amount(r.after_debt_cf)}</td></tr>)}</tbody></table></div></details>)}</div>}