-- Restructure business partners into a two-level classification.

do $$
begin
  if (select count(*) from public.client_categories_master) <> 2
     or (select count(*) from public.client_categories_master where category_name in ('得意先', '仕入先')) <> 2 then
    raise exception 'client_categories_master must contain exactly 得意先 and 仕入先 before this migration';
  end if;

  if (select count(*) from public.clients where company_name = '株式会社サンプルA') <> 1 then
    raise exception '株式会社サンプルA must exist exactly once in clients';
  end if;

  if (select count(*) from public.clients where company_name = '有限会社サンプルB') <> 1 then
    raise exception '有限会社サンプルB must exist exactly once in clients';
  end if;

  if not exists (
    select 1
    from public.clients c
    join public.client_categories_master category
      on category.client_categories_id = c.client_categories_id
    where c.company_name = '株式会社サンプルA'
      and category.category_name = '得意先'
  ) then
    raise exception '株式会社サンプルA must currently be classified as 得意先';
  end if;

  if not exists (
    select 1
    from public.clients c
    join public.client_categories_master category
      on category.client_categories_id = c.client_categories_id
    where c.company_name = '有限会社サンプルB'
      and category.category_name = '仕入先'
  ) then
    raise exception '有限会社サンプルB must currently be classified as 仕入先';
  end if;
end $$;

alter table public.client_categories_master
  add column if not exists category_code varchar(50);

update public.client_categories_master
set category_code = case category_name
  when '得意先' then 'customer'
  when '仕入先' then 'supplier'
end;

alter table public.client_categories_master
  alter column category_code set not null;

create unique index if not exists uq_client_categories_master_category_code
  on public.client_categories_master (category_code);

create table public.client_subcategories_master (
  client_subcategory_id bigint generated by default as identity primary key,
  client_categories_id bigint not null,
  subcategory_code varchar(50) not null,
  subcategory_name varchar(100) not null,
  display_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fk_client_subcategories_category
    foreign key (client_categories_id)
    references public.client_categories_master (client_categories_id)
    on update restrict
    on delete restrict,
  constraint uq_client_subcategories_category_code
    unique (client_categories_id, subcategory_code),
  constraint uq_client_subcategories_id_category
    unique (client_subcategory_id, client_categories_id)
);

insert into public.client_subcategories_master (
  client_categories_id,
  subcategory_code,
  subcategory_name,
  display_order
)
select
  category.client_categories_id,
  seed.subcategory_code,
  seed.subcategory_name,
  seed.display_order
from (
  values
    ('得意先', 'customer_tenant', 'テナント', 10),
    ('得意先', 'customer_other', 'その他', 20),
    ('仕入先', 'supplier_broker', '仲介業者', 10),
    ('仕入先', 'supplier_management_company', '管理会社', 20),
    ('仕入先', 'supplier_other', 'その他', 30)
) as seed(category_name, subcategory_code, subcategory_name, display_order)
join public.client_categories_master category
  on category.category_name = seed.category_name
on conflict (client_categories_id, subcategory_code) do update set
  subcategory_name = excluded.subcategory_name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

alter table public.client_subcategories_master enable row level security;

grant select on public.client_subcategories_master to authenticated;

create policy "client subcategories: active user reads subcategories"
  on public.client_subcategories_master
  for select
  to authenticated
  using (public.current_account_is_active());

alter table public.clients rename to clients_table;

alter table public.clients_table
  add column client_code varchar(50),
  add column client_subcategory_id bigint,
  add column contact_person_name varchar(100),
  add column contact_email varchar(255),
  add column contact_phone varchar(50),
  add column contact_department varchar(100),
  add column contact_position varchar(100);

create unique index uq_clients_table_client_code
  on public.clients_table (client_code)
  where client_code is not null;

update public.clients_table client
set client_subcategory_id = subcategory.client_subcategory_id
from public.client_subcategories_master subcategory
where client.company_name = '株式会社サンプルA'
  and subcategory.subcategory_code = 'customer_tenant'
  and subcategory.client_categories_id = client.client_categories_id;

update public.clients_table client
set client_subcategory_id = subcategory.client_subcategory_id
from public.client_subcategories_master subcategory
where client.company_name = '有限会社サンプルB'
  and subcategory.subcategory_code = 'supplier_broker'
  and subcategory.client_categories_id = client.client_categories_id;

do $$
begin
  if exists (
    select 1
    from public.clients_table
    where client_categories_id is null
       or client_subcategory_id is null
  ) then
    raise exception 'All clients must be assigned both a category and a subcategory';
  end if;
end $$;

alter table public.clients_table
  alter column client_categories_id set not null,
  alter column client_subcategory_id set not null,
  add constraint fk_clients_table_category_subcategory
    foreign key (client_subcategory_id, client_categories_id)
    references public.client_subcategories_master (
      client_subcategory_id,
      client_categories_id
    )
    on update restrict
    on delete restrict;

create index idx_clients_table_category
  on public.clients_table (client_categories_id);

create index idx_clients_table_subcategory
  on public.clients_table (client_subcategory_id);

comment on table public.clients_table is '取引先マスタ';
comment on table public.client_subcategories_master is '取引先の小分類マスタ';
comment on column public.clients_table.client_code is '取引先コード';
comment on column public.clients_table.contact_person_name is '担当者名';
comment on column public.clients_table.contact_email is '担当者メールアドレス';
comment on column public.clients_table.contact_phone is '担当者電話番号';
comment on column public.clients_table.contact_department is '担当者部署';
comment on column public.clients_table.contact_position is '担当者役職';
